from pydantic import BaseModel, Field
from typing import Literal
from datetime import datetime


class ItemMetadata(BaseModel):
    """
    Structured output from GPT-4o vision analysis of a clothing image.
    
    All fields except item_type and search_query are optional — GPT-4o
    may not be able to confidently identify every attribute from a photo.
    The search_query field is the most critical: a bad query produces
    useless comps regardless of how accurate the other fields are.
    """

    brand: str | None = None
    item_type: str                    # "denim jacket", "sneakers", "graphic tee"
    color: str | None = None
    size: str | None = None
    condition: Literal["poor", "fair", "good", "excellent"] | None = None
    material: str | None = None
    notable_details: list[str] = Field(default_factory=list)  # ["distressed knees", "vintage logo"]

    # The most important field — GPT-4o assembles this for eBay lookup
    # Good: "Levi's 501 jeans dark wash"
    # Bad: "vintage blue denim pants" (too generic, comps will be useless)
    search_query: str


class SoldComp(BaseModel):
    """
    A single eBay sold listing used as a raw price reference.
    
    These are the individual data points that feed into CompResult
    aggregation. Stored in raw_comps for UI display ("We found 23
    sales at $28–$58") and for debugging pricing outliers.
    """

    title: str
    sold_price: float
    currency: str = "USD"


class CompResult(BaseModel):
    """
    Aggregated pricing intelligence from eBay Browse API sold listings.
    
    suggested_price is set at median * 0.95 — intentionally priced
    slightly under market rate to move inventory quickly rather than
    optimizing for maximum margin. raw_comps are retained for UI
    display and potential future reanalysis without re-calling the API.
    """

    search_query: str
    sample_size: int
    low_price: float
    median_price: float
    high_price: float
    suggested_price: float
    raw_comps: list[SoldComp] = Field(default_factory=list)


class ScrapedComp(BaseModel):
    """
    A single listing scraped from a third-party resale platform.
    
    price_type distinguishes sold comps (ground truth) from active
    asking prices (directional only). The aggregator weights these
    differently — sold comps anchor the recommendation, asking prices
    provide positioning context. Poshmark returns asking prices only;
    Mercari and Depop return sold comps.
    """
    platform: str
    sold_price: float
    title: str
    price_type: Literal["sold", "asking"] = "sold"
    url: str | None = None
    sold_date: datetime | None = None
    condition: str | None = None


class PlatformPricing(BaseModel):
    """
    Aggregated price statistics for a single resale platform.
    
    Computed from a list of ScrapedComp or SoldComp records by the
    comp aggregator. min/median/max give the buyer a price range;
    sample_size signals how much to trust the numbers — a median
    from 4 comps is far less reliable than one from 40.
    """

    min_price: float
    median_price: float
    max_price: float
    sample_size: int
    price_type: Literal["sold", "asking"] = "sold"


class AggregatedPricing(BaseModel):
    """
    Cross-market pricing intelligence synthesized across all 4 sources.
    
    Each platform field is optional because any scraper can fail
    (rate limit, DOM change, zero results) without invalidating the
    entire result — partial data is still useful. recommended_platform
    is derived by the comp aggregator based on median price and sample
    size. pricing_confidence reflects data coverage: 'high' requires
    3+ platforms with 10+ comps each, 'medium' requires 2+ platforms,
    'low' is everything else.
    """

    ebay: PlatformPricing | None = None
    poshmark: PlatformPricing | None = None
    mercari: PlatformPricing | None = None
    depop: PlatformPricing | None = None
    recommended_platform: str | None = None
    pricing_confidence: Literal["low", "medium", "high"] = "low"


class ListingDraft(BaseModel):
    """
    A platform-specific listing draft ready for review and posting.
    
    Generated by GPT-4o text generation after pricing is complete.
    Each platform gets its own draft — Poshmark and eBay have different
    voice, format rules, and character limits that are enforced during
    post-processing validation after generation. hashtags are
    Poshmark-specific; the eBay draft always receives an empty list.
    """

    platform: Literal["poshmark", "ebay"]
    title: str
    description: str
    suggested_price: float
    category_hint: str
    hashtags: list[str] = Field(default_factory=list)


class AnalysisResult(BaseModel):
    """
    Complete pipeline output for a single item analysis.
    
    The top-level response model returned by POST /api/v1/items/analyze.
    Composes all downstream results — vision analysis, eBay pricing,
    and listing generation — into a single object. The listings list
    always contains exactly 2 drafts: one for Poshmark, one for eBay,
    in that order.
    """

    item: ItemMetadata
    comps: CompResult
    listings: list[ListingDraft]